# Generated by Django 3.2.2 on 2021-05-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_descuento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Descuento',
            new_name='Oferta',
        ),
    ]
