# Generated by Django 3.2.2 on 2021-05-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_descuento_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(default='CLP', max_length=3),
        ),
    ]
